### PR TITLE
Update FAQ for Actor overhead and green threads

### PR DESCRIPTION
**Pull request by thomastay**

### CODE REVIEW

**Comment by thomastay** [comment]
marked as draft as I noticed a link typo

**Comment by SeanTAllen** [comment]
I'm not comfortable with the change to say that Pony is green threads, I'd like to see the previous language mantained.

**Comment by SeanTAllen** [comment]
@thomastay the actor overhead entry looks good, can you do a separate PR from it and we can discuss the green threads changes separately?

**Comment by SeanTAllen** [comment]
I think "actor overhead" is slightly misleading. It should be "What is the memory overhead of an actor?"

I'm a little wary of the comparison to other languages. We need to step carefully there are even statements of fact that are made innocently can in certain contexts look like an attack on other languages which is something we want to avoid.

**Comment by thomastay** [comment]
I'd like to come up with a phrase that well describes pony's actors in terms of their weight.  Green threads is the technically incorrect phrase, but I can't think of another phrase that best conveys the lightweight nature of it. Maybe something like fibers? Terminology is not my strong suit as I don't have the formal training in this area.

RE: Comparison --> Agreed. I felt a bit uncomfortable putting that in, but I thought it might be helpful to have context, which is why i left it in with a disclaimer. Do you think I should remove it?

**Comment by SeanTAllen** [comment]
@thomastay I've been thinking about this. Is the FAQ really, "what's the actor overhead" or is it more "are actors lightweight like they are on BEAM"?

if its the latter, then a comparison of overhead to Elixir/Erlang makes a lot of sense.

**Comment by damon-kwok** [comment]
> You worry about actors and sending messages between them.
@thomastay You can directly call the method without sending messages between actors. Pony actors are more convenient than Go‘s `Goroutine` and Elixir/Erlang's `Actor`.

**Comment by thomastay** [comment]
@SeanTAllen exactly. I think even for people familiar with the Actor model, people still want to be certain that the overhead of an actor is not too high. That's why every Elixir talk ever begins with "BEAM processes are nothing like OS processes"...

Again, I don't want to start language competition. But as many people are unfamiliar with the Actor model, it's probably worth mentioning at least the ballpark that we're playing in; that is - how close are we to Elixir/Go? 

As I write this, I realize what I meant to convey is that our actors are just as lighweight as theirs are. Maybe we can just say that, instead of mentioning what size they are.

**Comment by SeanTAllen** [comment]
@thomastay Can you update this PR to not touch the green threads FAQ and instead add a new FAQ targeted at the "Are Pony actors lightweight like Elixir/Erlang actors?"

That FAQ answer could then go into something like "yes" and "you can use them like blah and blah like you would in E/E".

**Comment by SeanTAllen** [comment]
@thomastay I've opened a PR that would add a new section to the FAQ that yours could be included in. It's a "comparisons" section.

https://github.com/ponylang/ponylang-website/pull/580

**Comment by thomastay** [comment]
@SeanTAllen PTAL, thanks!

**Comment by SeanTAllen** [comment]
Awesome. Thanks @thomastay!

**Pull request merged**
