### PR TITLE
Last Week in Pony - July 2, 2023

### PR DESCRIPTION
**Pull request by SeanTAllen**

### CODE REVIEW

**Comment by rhagenson** [comment]
Planning on highlighting one of the papers this week https://www.ponylang.io/community/#papers

Not sure which I have covered and which I have not yet so I'll check on that before deciding which to highlight this week.

**Comment by SeanTAllen** [comment]
@rhagenson so deny capabilites came up during office hours that week. given that, i would skip it as it was in LWIP for last week.

**Comment by rhagenson** [comment]
Thank you for the reminder! I had forgotten that.

**Comment by rhagenson** [comment]
I am going to highlight https://www.ponylang.io/media/papers/a_string_of_ponies.pdf -- I need to give it a read again myself.

**Pull request merged**
