### PR TITLE
More interacting Readme.md

### PR DESCRIPTION
**Pull request by vikas28km**

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I'm not in favor of the combination of changes this PR.

Can you explain your reasoning behind each of the changes @vikas28km?

**Comment by vikas28km** [comment]
> I'm not in favor of the combination of changes this PR.
> 
> Can you explain your reasoning behind each of the changes @vikas28km?

I just try to make that conversation more polite and interacting.....

**Comment by vikas28km** [comment]
> > I'm not in favor of the combination of changes this PR.
> > Can you explain your reasoning behind each of the changes @vikas28km?
> 
> I just try to make that conversation more polite and interacting.....
> I'm sorry for hearing that from you :-(
> 
> Please forgive me for this, if you don't like it. Then, you can tell me, i will remove it :(

besides of all these,,

Can we be the friends??

**Comment by SeanTAllen** [comment]
I don't understand what "interacting" means in this context.

I don't see how the changes are any more polite than what is currently there. Can you explain case by case how it is more polite?

**Comment by vikas28km** [comment]
> I don't understand what "interacting" means in this context.
> 
> I don't see how the changes are any more polite than what is currently there. Can you explain case by case how it is more polite?

sorry,
I am new here. I can't explain you any more :(

**Comment by vikas28km** [comment]
Would you like to be friend??
I want to learn more from you..

**Comment by EpicEric** [comment]
Closing as low-quality contribution.

**Pull request closed without merging**
