### PR TITLE
Make color mode switcher more perceptible

### LINKED ISSUE #978: Color mode switcher
It's nice that you include a language switcher on your website. However, it's not exactly apparent that it is one. I guessed, it was and was proven right, but it could have an icon of sorts resembling light and dark.

### PR DESCRIPTION
**Pull request by shaedrich**
Fix #978

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I prefer the existing and don't find the icons to be any more "intuitive". I'd end up mousing over both of them. If we decide at sync to accept this change, this shouldn't be merged until PRs are open for patterns and the tutorial as well.

**Comment by SeanTAllen** [comment]
build failure can be ignored. we need to update to be able to the non-insiders version when we do a build check for a PR from a forked repo.

**Comment by jemc** [comment]
We discussed on today's Pony sync call.

I agree that the current nondescript toggle is not clear, and that it's better to choose a clearer icon.

I think showing a moon or sun icon that switches is confusing, because it's not clear whether it's showing the current state or future state. I was saying it might it be better to show an icon which is sun and moon together, which doesn't change when you change the state.

So I just [looked in the material icon set](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:brightness_4:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=sun) and I found an icon that shows a moon inside of sun called `brightness_4`. Are we able to use that icon inside this theme? If so, that would probably be ideal. Could you update this PR to use that icon for both states?

But please note that before we can merge this PR, we need to also have a corresponding PR in the [pony-tutorial](https://github.com/ponylang/pony-tutorial) and [pony-patterns](https://github.com/ponylang/pony-patterns) repos.

**Comment by shaedrich** [comment]
A text label would be nice, too, but I don't think, that's possible with mkdocs. So, I've changed the icon accordingly, and made the changes in [pony-tutorial](https://github.com/ponylang/pony-tutorial) and ([pony-patterns](https://github.com/ponylang/pony-patterns) respectively.

**Comment by shaedrich** [comment]
> A text label would be nice, too (additionally to the tooltip), but I don't think, that's possible with mkdocs.

@SeanTAllen I just listened to your Sync and yeah, the state is already visible on the site, and therefore, a label would be somewhat redundant. So just forget what I said about the label 😅

**Pull request merged**
